environment: test
db:
  test:
    host: localhost
    port: 5432
    user: postgres
    password: 1
    dbname: arrs_planning_test
  live:
    host: localhost
    port: 5432
    user: postgres
    password: 1
    dbname: arrs_planning